title: Facebook Privacy Policy
description: Privacy Policy for Facebook
baseurl: /
url: https://teslations.github.io/facebook-privacy-policy/
# The theme is optional, but good for customization
theme: jekyll-theme-cayman
